### ISSUE TITLE
Set assembly name to ClayOne.ComposerCore

### ISSUE THREAD

**Issue by a3dho3yn** [clay-one/composer-core#15]

**Comment by a3dho3yn** [comment]
This is a breaking change. @iravanchi are you ok with this?

**Comment by iravanchi** [comment]
Many projects don't prefix the organization name on their product name / assembly / package names. Example: log4net.

I insist NOT having "ClayOne" in namespaces, and we kinda have to include "ClayOne" in NuGET package names to make them unique. But for the assembly name, either way is okay and I don't have any strong opinion toward any. What do you think?

@a3dho3yn @kiapanahi @faridprogrammer

**Comment by iravanchi** [comment]
As there is not enough feedback on this, and the current naming scheme seems at least reasonable, I am closing this issue.
